#--------------------------------------+---------------------------------------8
#                                                                              |
# Deploys the Control Plane                                                    |
#                                                                              |
#--------------------------------------+---------------------------------------8


name:                                  Deploys the control plane defined in $(deployerfolder) $(libraryfolder)

parameters:

  - name:                              control_plane_name
    displayName:                       "Control Plane Name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           CTRL-NOEU-MGT01

  - name:                              use_deployer
    displayName:                       Run on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              reset
    displayName:                       Force a re-install - may require multiple re-runs
    type:                              boolean
    default:                           false

trigger:                               none


variables:

- group:                               SDAF-${{ parameters.control_plane_name }}

#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 01-deploy-control-plane.yaml from the code repository                  |
#                                                                              |
#--------------------------------------+---------------------------------------8

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\01-deploy-control-plane.yaml@sap-automation
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          use_deployer:                ${{ parameters.use_deployer }}
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          connection_name:             $(AZURE_CONNECTION_NAME)
          force_reset:                 ${{ parameters.reset }}
