#--------------------------------------+---------------------------------------8
#                                                                              |
# Deploys the Workload Zone                                                    |
#                                                                              |
#--------------------------------------+---------------------------------------8

name:                                  Deploying the SAP Workload zone defined in $(workload_zone_folder)

parameters:
  - name:                              workload_zone_name
    displayName:                       "Workload zone name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           TEST-NOEU-SAP01

  - name:                              control_plane_name
    displayName:                       "Control plane name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           CTRL-NOEU-MGT01

  - name:                              inherit_settings
    displayName:                       Inherit Terraform state file information from control plane
    type:                              boolean
    default:                           true

  - name:                              test
    displayName:                       Test only
    type:                              boolean
    default:                           false

#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 02-sap-workload-zone.yaml from the code repository                     |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8

trigger:                               none

pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\02-sap-workload-zone.yaml@sap-automation
        parameters:
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          control_plane_name:          ${{ parameters.control_plane_name }}
          inherit_settings:            ${{ parameters.inherit_settings }}
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          test:                        ${{ parameters.test }}
          
