#--------------------------------------+---------------------------------------8
#                                                                              |
# Deploys the Infrastructure for the SAP System                                |
#                                                                              |
#--------------------------------------+---------------------------------------8

name:                                  SAP Infrastructure Deployment $(sap_system_folder)

parameters:
  - name:                              sap_system
    displayName:                       "SAP System name, use the following syntax: ENV-LOCA-VNET-SID"
    type:                              string
    default:                           TEST-NOEU-SAP01-X00

  - name:                              workload_zone_name
    displayName:                       "Workload Zone name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           TEST-NOEU-SAP01

  - name:                              test
    displayName:                       Test only
    type:                              boolean
    default:                           false

#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 03-sap-system-deployment from the code repository                      |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8
trigger:                               none

pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]
  vmImage:                             ubuntu-latest

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\03-sap-system-deployment.yaml@sap-automation
        parameters:
          sap_system:                  ${{ parameters.sap_system }}
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          test:                        ${{ parameters.test }}
