#--------------------------------------+---------------------------------------8
#                                                                              |
# Download the software from SAP                                               |
#                                                                              |
#--------------------------------------+---------------------------------------8
name:                                  SAP Software download $(bom) $(environment_code) $(location_code)

parameters:
  - name:                              bom_base_name
    displayName:                       Name of Bill of Materials (BoM)
    type:                              string
    values:
      - S42023SPS00_v0003ms
      - S42023SPS00_v0004ms (dynamic)
      - S42022SPS00_v0005ms
      - S42022SPS00_v0006ms (dynamic)
      - S42021ISS00_v0001ms
      - S42020ISS00_v0003ms
      - S41909ISS00_v0011ms      
      - S41909ISS00_v0012ms (dynamic)      
      - NW750SPS25_v0001ms
      - NW750_HANA_v0004ms
      - NW752SPS09_v0001ms
      - NW750SPS20_DB2_v0001ms
      - NW750_ORACLE_19_v0001ms
      - NW750SPS25_JAVA_v0001ms
      - NW750SPS20_SYBASE_v0001ms
      - NW750_ORACLE_19_ASM_v0001ms
      - NW750_MSSQL_v0001ms
      - NW752_MSSQL_v0001ms
      - NW_MSSQL_v0001ms
      - ORACLE_19_00_v0003ms
      - ORACLE_19_00_ASM_v0001ms      
      - DB2_UDB_11_5_v0001ms
      - ORACLE_19_00_ORA_MSID_v0002ms
      - ERP6_EHP8_WIN_MSS2019_v0001ms
      - ERP6_EHP8_WIN_MSS2016_v0001ms
      - ERP6_EHP8_LNX_DB2UDB_11_5_v0001ms
      - HCMT_v0002ms
      - BW4HANA2021SPS01_v0003ms
      - HANA_2_00_059_v0010ms
      - HANA_2_00_067_v0006ms
      - HANA_2_00_076_v0001ms
      - HANA_2_00_071_v0001ms

  - name:                              bom_override_name
    displayName:                       Custom Name of Bill of Materials (BoM)
    default:                           ' '
    type:                              string

  - name:                              environment
    displayName:                       Control Plane Environment
    default:                           MGMT

  - name:                              region
    displayName:                       Control Plane (SAP Library) location code
    type:                              string
    default:                           WEEU

  - name:                              extra_params
    displayName:                       Extra Parameters
    type:                              string
    default:                           ' '

  - name:                              re_download
    displayName:                       Re-download software from SAP
    type:                              boolean
    default:                           false

#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 04-sap-software-download.yaml from the code repository                 |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8
trigger:                               none


pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]

extends:
  template:                            ./resources_including_samples.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\04-sap-software-download.yaml@sap-automation
        parameters:
          bom_base_name:               ${{ replace(coalesce(replace(parameters.bom_override_name,' ',''), split(parameters.bom_base_name,' ')[0] ),' ','') }}
          environment:                 ${{ parameters.environment }}
          region:                      ${{ parameters.region }}
          re_download:                 ${{ parameters.re_download }}
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          sample_repo_path:            $(Build.SourcesDirectory)/samples
          ExtraParams:                 ${{ parameters.extra_params }}
