#--------------------------------------+---------------------------------------8
#                                                                              |
# Download the software from SAP                                               |
#                                                                              |
#--------------------------------------+---------------------------------------8
name:                                  SAP Software download $(bom) $(environment_code) $(location_code)

parameters:
  - name:                              bom_base_name
    displayName:                       Name of Bill of Materials (BoM)
    type:                              string
    values:
      - S42023SPS00_v0003ms (HANA_2_00_077)
      - S42023SPS00_v0004ms (HANA_2_00_077 - dynamic)
      
      - S42022SPS00_v0004ms (HANA_2_00_077 - dynamic)
      - S42022SPS00_v0005ms (HANA_2_00_076)
      - S42022SPS00_v0006ms (HANA_2_00_077)
      
      - S42021ISS00_v0003ms (HANA_2_00_067)
      
      - S42020ISS00_v0004ms (HANA_2_00_067 - dynamic)
      - S42020SPS03_v0005ms (HANA_2_00_067)
      
      - S41909SPS03_v0012ms (HANA_2_00_059 - dynamic)
      - S41909ISS00_v0013ms (HANA_2_00_059)
      
      - NW750SPS20_v0005ms (HANA_2_00_067)
      - NW750SPS20_v0006ms (HANA_2_00_067 - dynamic)
      - NW750SPS25_JAVA_v0001ms (HANA_2_00_067)
      - NW752SPS09_v0002ms (HANA_2_00_067)
      - NW750SPS25_JAVA__HANA_v0001ms (HANA_2_00_067)
    
      - NW750SPS20_DB2_v0002ms (DB2_UDB_11_5)
    
      - NW750_ORACLE_19_v0001ms (Oracle_19)
      - NW750_ORACLE_19_ASM_v0001ms (Oracle_19)
      - NW750SPS25_JAVA_Oracle_19_00_v0001ms (Oracle_19)
    
      - NW750SPS20_SYBASE_v0003ms (ASE_16_0_3)
    
      - NW750_MSSQL_v0003ms (MSSQL_2019)
      
      - HANA_2_00_059_v0011ms
      - HANA_2_00_067_v0006ms
      - HANA_2_00_076_v0001ms
      - HANA_2_00_077_v0002ms

      - DB2_UDB_11_5_v0001ms
      
      - ORACLE_19_00_v0003ms
      - ORACLE_19_00_ASM_v0001ms
      - ORACLE_19_00_ORA_MSID_v0002ms

      - MSSQLSRV_2019_v0001ms
      
      - SYBASE_1603SP15_v0003ms


  - name:                              bom_override_name
    displayName:                       Custom Name of Bill of Materials (BoM)
    default:                           ' '
    type:                              string

  - name:                              environment
    displayName:                       Control Plane Environment
    default:                           MGMT

  - name:                              region
    displayName:                       Control Plane (SAP Library) location code
    type:                              string
    default:                           WEEU

  - name:                              extra_params
    displayName:                       Extra Parameters
    type:                              string
    default:                           ' '

  - name:                              re_download
    displayName:                       Re-download software from SAP
    type:                              boolean
    default:                           false

#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 04-sap-software-download.yaml from the code repository                 |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8
trigger:                               none


pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]

extends:
  template:                            ./resources_including_samples.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\04-sap-software-download.yaml@sap-automation
        parameters:
          bom_base_name:               ${{ replace(coalesce(replace(parameters.bom_override_name,' ',''), split(parameters.bom_base_name,' ')[0] ),' ','') }}
          environment:                 ${{ parameters.environment }}
          region:                      ${{ parameters.region }}
          re_download:                 ${{ parameters.re_download }}
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          sample_repo_path:            $(Build.SourcesDirectory)/samples
          ExtraParams:                 ${{ parameters.extra_params }}
