#--------------------------------------+---------------------------------------8
#                                                                              |
# Download the software from SAP                                               |
#                                                                              |
#--------------------------------------+---------------------------------------8
name:                                  SAP Software download $(bom) $(environment_code) $(location_code)

parameters:
  - name:                              bom_base_name
    displayName:                       Name of Bill of Materials (BoM)
    type: string
    default:
    values:
      - S4HANA_2021_ISS_v0001ms
      - S4HANA_2021_ISS_v0002ms
      - S42020SPS04_v0001ms
      - S42020SPS04_v0002ms
      - S41909SPS03_v0011ms
      - S41909SPS03_v0012ms
      - HCMT_v0002ms
      - BW4HANA2021SPS01_v0003ms
      - HANA_2_00_055_v0006ms
      - HANA_2_00_059_v0004ms
      - HANA_2_00_066_v0001ms
      - NW750SPS20_v0004ms
      - NW752SPS09_v0001ms
      - NW750SPS20_DB2_v0001ms
      - NW750SPS25_JAVA_v0001ms
      - ORACLE_19_00_v0003ms
      - ORACLE_19_00_ASM_v0001ms
      - NW750SPS20_DB2_v0001ms
      - DB2_UDB_11_5_v0001ms
      - ORACLE_19_00_ORA_MSID_v0002ms
      - ERP6_EHP8_WIN_MSS2019_v0001ms
      - ERP6_EHP8_WIN_MSS2016_v0001ms
      - ERP6_EHP8_LNX_DB2UDB_11_5_v0001ms
      - NW_MSSQL_v0001ms

  - name:                              environment
    displayName:                       Control Plane Environment
    default:                           MGMT

  - name:                              region
    displayName:                       Control Plane (SAP Library) location code
    type:                              string
    default:                           WEEU

  - name:                              extra_params
    displayName:                       Extra Parameters
    type:                              string
    default:                           " "

  - name:                              re_download
    displayName:                       Re-download software from SAP
    type:                              boolean
    default:                           false

#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 04-sap-software-download.yaml from the code repository                 |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8
trigger:                               none


pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]

extends:
  template:                            ./resources_including_samples.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\04-sap-software-download.yaml@sap-automation
        parameters:
          bom_base_name:               ${{ parameters.bom_base_name }}
          environment:                 ${{ parameters.environment }}
          region:                      ${{ parameters.region }}
          re_download:                 ${{ parameters.re_download }}
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          sample_repo_path:            $(Build.SourcesDirectory)/samples
          ExtraParams:                 ${{ parameters.extra_params }}
