---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline performs the software installation             |
# |              and must run on a self hosted deployment agent                |
# |                      due to long run time                                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                  OS Configuration and SAP Installation $(sap_system_folder) $(bom)

parameters:
  - name:                              sap_system_configuration_name
    displayName:                       "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
    type:                              string
    default:                           DEV-WEEU-SAP01-X00

  - name:                              environment
    displayName:                       Workload Environment (DEV, QUA, PRD, ...)
    type:                              string
    default:                           DEV

  - name:                              bom_base_name
    displayName:                       Bill of Materials name
    type:                              string
    values:
      - S42023SPS00_v0003ms (HANA_2_00_077)
      - S42023SPS00_v0004ms (HANA_2_00_077 - dynamic)
      
      - S42022SPS00_v0004ms (HANA_2_00_077 - dynamic)
      - S42022SPS00_v0005ms (HANA_2_00_076)
      - S42022SPS00_v0006ms (HANA_2_00_077)
      
      - S42021ISS00_v0003ms (HANA_2_00_067)
      
      - S42020ISS00_v0004ms (HANA_2_00_067 - dynamic)
      - S42020SPS03_v0005ms (HANA_2_00_067)
      
      - S41909SPS03_v0012ms (HANA_2_00_059 - dynamic)
      - S41909ISS00_v0013ms (HANA_2_00_059)
      
      - NW750SPS20_v0005ms (HANA_2_00_067)
      - NW750SPS20_v0006ms (HANA_2_00_067 - dynamic)
      - NW750SPS25_JAVA_v0001ms (HANA_2_00_067)
      - NW752SPS09_v0002ms (HANA_2_00_067)
      - NW750SPS25_JAVA__HANA_v0001ms (HANA_2_00_067)
    
      - NW750SPS20_DB2_v0002ms (DB2_UDB_11_5)
    
      - NW750_ORACLE_19_v0001ms (Oracle_19)
      - NW750_ORACLE_19_ASM_v0001ms (Oracle_19)
      - NW750SPS25_JAVA_Oracle_19_00_v0001ms (Oracle_19)
    
      - NW750SPS20_SYBASE_v0003ms (ASE_16_0_3)
    
      - NW750_MSSQL_v0003ms (MSSQL_2019)
      
      - HANA_2_00_059_v0011ms
      - HANA_2_00_067_v0006ms
      - HANA_2_00_076_v0001ms
      - HANA_2_00_077_v0002ms

      - DB2_UDB_11_5_v0001ms
      
      - ORACLE_19_00_v0003ms
      - ORACLE_19_00_ASM_v0001ms
      - ORACLE_19_00_ORA_MSID_v0002ms

      - MSSQLSRV_2019_v0001ms
      
      - SYBASE_1603SP15_v0003ms

  - name:                              bom_override_name
    displayName:                       Custom Name of Bill of Materials (BoM)
    default:                           ' '
    type:                              string
  
  - name:                              extra_params
    displayName:                       Extra Parameters
    type:                              string
    default:                           ' '

  - name:                              base_os_configuration
    displayName:                       Core Operating System Configuration
    type:                              boolean
    default:                           true

  - name:                              sap_os_configuration
    displayName:                       SAP Operating System Configuration
    type:                              boolean
    default:                           true

  - name:                              bom_processing
    displayName:                       Local software download
    type:                              boolean
    default:                           true

  - name:                              scs_installation
    displayName:                       SCS Installation & High Availability Configuration
    type:                              boolean
    default:                           true

  - name:                              database_install
    displayName:                       Database Installation
    type:                              boolean
    default:                           true

  - name:                              db_load
    displayName:                       Database Load
    type:                              boolean
    default:                           true

  - name:                              high_availability_configuration
    displayName:                       Database High Availability Configuration
    type:                              boolean
    default:                           true

  - name:                              pas_installation
    displayName:                       Primary Application Server Installation
    type:                              boolean
    default:                           true

  - name:                              application_server_installation
    displayName:                       Application Server Installation
    type:                              boolean
    default:                           true

  - name:                              webdispatcher_installation
    displayName:                       Web Dispatcher Installation
    type:                              boolean
    default:                           false

  - name:                              sap_on_azure_quality_checks
    displayName:                       SAP on Azure Quality Checks
    type:                              boolean
    default:                           false

  - name:                              post_configuration_actions
    displayName:                       Post Configuration Actions
    type:                              boolean
    default:                           false

  - name:                               ams_provider
    displayName:                        Configure AMS Provider
    type:                               boolean
    default:                            false


# 20220929 MKD - ACSS Registration <BEGIN>
  - name:                              acss_registration
    displayName:                       Register System in ACSS
    type:                              boolean
    default:                           true

  - name:                              acss_environment
    displayName:                       ACSS Prod/NonProd
    type:                              string
    values:
      - NonProd
      - Prod

  - name:                              acss_sap_product
    displayName:                       System Type
    type:                              string
    values:
      - S4HANA
      - ECC
      - Other
# 20220929 MKD - ACSS Registration <END>


#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 05-DB-and-SAP-installation.yaml from the code repository               |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8
trigger:                               none

pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\05-DB-and-SAP-installation.yaml@sap-automation
        parameters:
          sap_system_configuration_name:   ${{ parameters.sap_system_configuration_name }}
          environment:                     ${{ parameters.environment }}
          bom_base_name:                   ${{ replace(coalesce(replace(parameters.bom_override_name,' ',''), split(parameters.bom_base_name,' ')[0] ),' ','') }}
          base_os_configuration:           ${{ parameters.base_os_configuration }}
          sap_os_configuration:            ${{ parameters.sap_os_configuration }}
          bom_processing:                  ${{ parameters.bom_processing }}
          database_install:                ${{ parameters.database_install }}
          scs_installation:                ${{ parameters.scs_installation }}
          db_load:                         ${{ parameters.db_load }}
          high_availability_configuration: ${{ parameters.high_availability_configuration }}
          pas_installation:                ${{ parameters.pas_installation }}
          application_server_installation: ${{ parameters.application_server_installation }}
          webdispatcher_installation:      ${{ parameters.webdispatcher_installation }}
          sap_on_azure_quality_checks:     ${{ parameters.sap_on_azure_quality_checks }}
          post_configuration_actions:      ${{ parameters.post_configuration_actions }}
          acss_registration:               ${{ parameters.acss_registration }}
          acss_environment:                ${{ parameters.acss_environment }}
          acss_sap_product:                ${{ parameters.acss_sap_product }}
          ams_provider:                    ${{ parameters.ams_provider }}
          sap_automation_repo_path:        $(Build.SourcesDirectory)/sap-automation
          config_repo_path:                $(Build.SourcesDirectory)/config
          extra_params:                    ${{ parameters.extra_params }}
