---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline performs the software installation             |
# |              and must run on a self hosted deployment agent                |
# |                      due to long run time                                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                  OS Configuration and SAP Installation using SAP CAL $(sap_system_folder)

parameters:
  - name:                              sap_system_configuration_name
    displayName:                       "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
    type:                              string
    default:                           DEV-WEEU-SAP01-X00

  - name:                              environment
    displayName:                       Workload Environment (DEV, QUA, PRD, ...)
    type:                              string
    default:                           DEV

  - name:                              sap_cal_product_name
    displayName:                       SAP CAL Product Name
    type:                              string
    values:
      - S/4HANA_2023-Initial_Shipment_Stack
      - S/4HANA_2022-Initial_Shipment_Stack
      - S/4HANA_2021-Initial_Shipment_Stack
      - S/4HANA_2022-FPS_01_022023
      - S/4HANA_2022-FPS_02_052023
      - S/4HANA_2021-FPS_02_052022
      - S/4HANA_2021-FPS_01_022022
      - S/4HANA_2021-04_052023
      - S/4HANA_2021-03_112022
      - S/4HANA 2020-04_052022

  - name:                              extra_params
    displayName:                       Extra Parameters
    type:                              string
    default:                           " "

  - name:                              base_os_configuration
    displayName:                       Core Operating System Configuration
    type:                              boolean
    default:                           true

  - name:                              sap_os_configuration
    displayName:                       SAP Operating System Configuration
    type:                              boolean
    default:                           true

  - name:                              sapcal_integration
    displayName:                       SAP CAL Integration
    type:                              boolean
    default:                           true

# 20220929 MKD - ACSS Registration <BEGIN>
  - name:                              acss_registration
    displayName:                       Register System in ACSS
    type:                              boolean
    default:                           false

  - name:                              acss_environment
    displayName:                       ACSS Prod/NonProd
    type:                              string
    values:
      - NonProd
      - Prod

  - name:                              acss_sap_product
    displayName:                       System Type
    type:                              string
    values:
      - S4HANA
      - ECC
      - Other
# 20220929 MKD - ACSS Registration <END>


#--------------------------------------+---------------------------------------8
#                                                                              |
# Calls 07-sap-cal-installation.yaml from the code repository                  |
# If an Agent pool is defined it will be used otherwise Microsoft hosted       |
#                                                                              |
#--------------------------------------+---------------------------------------8
trigger:                               none

pool:
  name:                                $[coalesce(variables['POOL'], variables['Agent'])]

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\07-sap-cal-installation.yaml@sap-automation
        parameters:
          sap_system_configuration_name:   ${{ parameters.sap_system_configuration_name }}
          environment:                     ${{ parameters.environment }}
          base_os_configuration:           ${{ parameters.base_os_configuration }}
          sap_os_configuration:            ${{ parameters.sap_os_configuration }}
          acss_registration:               ${{ parameters.acss_registration }}
          acss_environment:                ${{ parameters.acss_environment }}
          acss_sap_product:                ${{ parameters.acss_sap_product }}
          sap_cal_product_name:            ${{ parameters.sap_cal_product_name }}
          sapcal_integration:              ${{ parameters.sapcal_integration }}
          sap_automation_repo_path:        $(Build.SourcesDirectory)/sap-automation
          config_repo_path:                $(Build.SourcesDirectory)/config
          extra_params:                    ${{ parameters.extra_params }}
