# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the SAP systems, the workload zone (landscape)  |
# |      and the region via ARM resource group deletion.                       |
# |                                                                            |
# |      The pipeline can be used as fallback in case the terraform            |
# |      destroy doesn't remove everything.                                    |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                  Remove deployment
parameters:
  - name:                              cleanup_sap
    displayName:                       Remove the SAP system
    type:                              boolean
    default:                           true

  - name:                              sap_system
    displayName:                       "SAP System SID, use this format: ENV-LOCA-VNET-SID"
    type:                              string
    default:                           X00

  - name:                              cleanup_workload_zone
    displayName:                       Remove the SAP workload zone
    type:                              boolean
    default:                           true

  - name:                              workload_zone_name
    displayName:                       "SAP workload zone configuration name, use this format: ENV-LOCA-VNET"
    type:                              string
    default:                           TEST-NOEU-SAP01

  - name:                              cleanup_control_plane
    displayName:                       Remove the control plane
    type:                              boolean
    default:                           true

  - name:                              control_plane_name
    displayName:                       "Deployer configuration name, use this format: ENV-LOCA-VNET"
    type:                              string
    default:                           CTRL-NOEU-MGT01



trigger:                               none

pool:
  vmImage:                             ubuntu-latest


variables:
  - group:                             SDAF-${{ parameters.workload_zone_name }}
extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\11-remover-arm-fallback.yaml@sap-automation
        parameters:
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          cleanup_sap:                 ${{ parameters.cleanup_sap }}
          sap_system:                  ${{ parameters.sap_system }}
          cleanup_workload_zone:       ${{ parameters.cleanup_workload_zone }}
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          cleanup_control_plane:       ${{ parameters.cleanup_control_plane }}
          control_plane_name:          ${{ parameters.control_plane_name }}
          workload_zone_connection:    $(AZURE_CONNECTION_NAME)
