---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the Control Plane via Terraform.                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                  Remove Control Plane

parameters:
  - name:                              control_plane_name
    displayName:                       "Control Plane Name name, use this format: ENV-LOCA-VNET"
    type:                              string
    default:                           CTRL-NOEU-MGT01

  - name:                              use_deployer
    displayName:                       Run removal on self hosted agent
    type:                              boolean
    default:                           false

trigger:                               none


variables:

  - group:                               SDAF-${{ parameters.control_plane_name }}

pool:
  name:                                $[coalesce(variables['run_on'], variables['Agent'])]

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\12-remove-control-plane.yaml@sap-automation
        parameters:
          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          control_plane_name:          ${{ parameters.control_plane_name }}
          use_deployer:                ${{ parameters.use_deployer }}
          connection_name:             $(AZURE_CONNECTION_NAME)
