name:                                  Create Deployer Configuration

parameters:
  - name:                              control_plane_name
    displayName:                       Deployer Environment name (MGMT, DEV, QA, PRD, ...)
    type:                              string
    default:                           MGMT-NOEU-DEP01

  - name:                              workload_zone_name
    displayName:                       Workload zone name (MGMT, DEV, QA, PRD, ...)
    type:                              string
    default:                           MGMT-NOEU-DEP01

  - name:                              firewall
    displayName:                       Deploy Azure Firewall
    type:                              boolean
    default:                           true

  - name:                              bastion
    displayName:                       Deploy Azure Bastion Service
    type:                              boolean
    default:                           true

  - name:                              webapp
    displayName:                       Deploy SDAF Web App
    type:                              boolean
    default:                           true

  - name:                              deployer_count
    displayName:                       Number of deployers to deploy
    type:                              number
    default:                           1

  - name:                              address_prefix
    displayName:                       Address prefix for the management network
    type:                              string
    default:                           10.170.20


  - name:                              identity
    displayName:                       Use a Service Principal for deployments (legacy), unchecking will use a Managed Identity.
    type:                              boolean
    default:                           false

  - name:                              msi_identity
    displayName:                       Provide the Azure resource identifier for the Managed Identity MSI to use (optional)
    type:                              string
    default:                           ' '

trigger:                               none


variables:

- group:                               SDAF-${{ parameters.control_plane_name }}

extends:
  template:                            ./resources.yml
  parameters:
    stages:
      - template:                      deploy\pipelines\22-sample-deployer-config.yaml@sap-automation
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          firewall:                    ${{ parameters.firewall }}
          bastion:                     ${{ parameters.bastion }}
          webapp:                      ${{ parameters.webapp }}
          deployer_count:              ${{ parameters.deployer_count }}
          address_prefix:              ${{ parameters.address_prefix }}
          identity:                    ${{ parameters.identity }}
          msi_identity:                ${{ parameters.msi_identity }}

          sap_automation_repo_path:    $(Build.SourcesDirectory)/sap-automation
          config_repo_path:            $(Build.SourcesDirectory)/config
          connection_name:             $(AZURE_CONNECTION_NAME)
