resources:
  repositories:
    - repository: sap-automation
      type: git
      name: sap deployment automation framework/sap-automation
      ref:  refs/heads/main

parameters:
  - name: stages
    type: stageList
    default: []

stages:
  - ${{ parameters.stages }}
